// flow-typed signature: 3ff2ab72864063ca871a1dc9ad2b411d
// flow-typed version: <<STUB>>/email-validator_v^2.0.4/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'email-validator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'email-validator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'email-validator/index.cjs' {
  declare module.exports: any;
}

declare module 'email-validator/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'email-validator/index.cjs.js' {
  declare module.exports: $Exports<'email-validator/index.cjs'>;
}
declare module 'email-validator/index' {
  declare module.exports: $Exports<'email-validator'>;
}
declare module 'email-validator/index.js' {
  declare module.exports: $Exports<'email-validator'>;
}
declare module 'email-validator/test.js' {
  declare module.exports: $Exports<'email-validator/test'>;
}
