// flow-typed signature: 647b031af868419214d174f320289847
// flow-typed version: <<STUB>>/mock-async-storage_v^2.1.0/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mock-async-storage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mock-async-storage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mock-async-storage/lib/__tests__/mockAsyncStorage.spec' {
  declare module.exports: any;
}

declare module 'mock-async-storage/lib/index' {
  declare module.exports: any;
}

declare module 'mock-async-storage/lib/mockAsyncStorage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mock-async-storage/lib/__tests__/mockAsyncStorage.spec.js' {
  declare module.exports: $Exports<'mock-async-storage/lib/__tests__/mockAsyncStorage.spec'>;
}
declare module 'mock-async-storage/lib/index.js' {
  declare module.exports: $Exports<'mock-async-storage/lib/index'>;
}
declare module 'mock-async-storage/lib/mockAsyncStorage.js' {
  declare module.exports: $Exports<'mock-async-storage/lib/mockAsyncStorage'>;
}
