// flow-typed signature: 6f30e36f0d0c46b5dadaad5066d83717
// flow-typed version: <<STUB>>/react-native-material-dropdown_v^0.11.1/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-material-dropdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-material-dropdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-material-dropdown/src/components/dropdown/index' {
  declare module.exports: any;
}

declare module 'react-native-material-dropdown/src/components/dropdown/styles' {
  declare module.exports: any;
}

declare module 'react-native-material-dropdown/src/components/item/index' {
  declare module.exports: any;
}

declare module 'react-native-material-dropdown/src/components/item/styles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-material-dropdown/index' {
  declare module.exports: $Exports<'react-native-material-dropdown'>;
}
declare module 'react-native-material-dropdown/index.js' {
  declare module.exports: $Exports<'react-native-material-dropdown'>;
}
declare module 'react-native-material-dropdown/src/components/dropdown/index.js' {
  declare module.exports: $Exports<'react-native-material-dropdown/src/components/dropdown/index'>;
}
declare module 'react-native-material-dropdown/src/components/dropdown/styles.js' {
  declare module.exports: $Exports<'react-native-material-dropdown/src/components/dropdown/styles'>;
}
declare module 'react-native-material-dropdown/src/components/item/index.js' {
  declare module.exports: $Exports<'react-native-material-dropdown/src/components/item/index'>;
}
declare module 'react-native-material-dropdown/src/components/item/styles.js' {
  declare module.exports: $Exports<'react-native-material-dropdown/src/components/item/styles'>;
}
